name: 22f3002542@ds.study.iitm.ac.in

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display Email
        run: echo "Triggered by 22f3002542@ds.study.iitm.ac.in"
